packages:
  # Astro site for stub project
  - 'test/website-types'
  # Astro site for nanostores project
  - 'test/website-nanostores'
  # Astro site for nanostores project (multiple entrypoints)
  - 'test/website-nanostores-multiple-ep'
  - 'test/website-semi-custom-layout'
  - 'test/website-custom-layout'
